apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fluentd.fullname" . }}-secrets
  namespace: logging
  labels:
    app: {{ template "fluentd.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
data:
  {{ if eq .Values.output.type "cloudwatch" -}}
  aws-access-key: {{ .Values.output.cloudwatch.accessKey | b64enc | quote }}
  aws-secret-key: {{ .Values.output.cloudwatch.secretKey | b64enc | quote }}
  aws-region: {{ .Values.output.cloudwatch.region | b64enc | quote }}
  {{- end }}
